language: node_js
node_js:
  - "6"
deploy:
  provider: npm
  email: antirek@yandex.ru
  api_key:
    secure: rRWavhsKDtbFmxlYNIGXRWzelJMzjdfTBxpGwl3tUVEKBr+0vnhd0/V35hpxcsT2IQY8342s7f86MxobKEYysiWrrtPyIpAqUdBWsad6rRCoxOV3lwmS9W/uu1Stfg90/0qYDrziMr+r0w6cvNKy5d17cmdZQv0aFvx11dF8vGGw+gENFyTNQ4idTyLhxLjg6iEfZ2OwmSu7wNdxbTmVQyyIlZgLXt9WVt7cda5F+/L8Y7x9kXRlwNr6Z4URWllmhlo7YaTmvPlxaznK7kNoV6IRa3OYxg/BNaSXu5mjAx5gKAP+FoO8nrj5B/rLVYUeG5d6WRc/kTQ4rM23nV0Bl+yt5QTGYfQgTVk2rwKih5bF0cHPcCrUj+encflzjZaFNQeyPS5QpyOVCid+Zb2wHyS6J99yz/UfbGIpH7ZTfcdQexmfrNA5tk9uonxUyDDLatAcVuYDLwgqA84qBuYiPo/5KZUuPRoEK2Fc3OgXRshofweld4bc0/uM6xjyuleS56OvyBgJ7XZtopOL8fJF9eL87cLhILcETbPD6mBeE798KPFILE93vqsp4EWsuxB8LYWe43aetIjchUDd5v+y4iVhCEo8Kb6lp0c9CnWS96moK/iYpxcBJDBejEQeAY1GtFU7czqs0zZQj/mx1uy45uuLZsVMe35Ol88tUNQfMcY=
  on:
    repo: getbeebon/reporter
